### ISSUE TITLE
Question about building

### ISSUE THREAD

**Issue by tcrowe** [MatthiasWinkelmann/redis-fs#1]
Hi @MatthiasWinkelmann I'm having a basic problem building. I don't think it's a problem with the repo but more inexperience on my side building a go app.

I did:

```sh
make get-deps # i think it worked
make build # error
make # error
```

```txt
tcrowe:redis-fs/ (master) $ make build
# github.com/MatthiasWinkelmann/redis-fs/redisfs
src/github.com/MatthiasWinkelmann/redis-fs/redisfs/file.go:19:2: cannot use file (type *redisFile) as type nodefs.File in return argument:
	*redisFile does not implement nodefs.File (missing Flock method)
make: *** [build] Error 2

tcrowe:redis-fs/ (master) $ make
# _/Users/tcrowe/git/redis-fs/redisfs
redisfs/file.go:19:2: cannot use file (type *redisFile) as type nodefs.File in return argument:
	*redisFile does not implement nodefs.File (missing Flock method)
FAIL	_/Users/tcrowe/git/redis-fs/redisfs [build failed]
make: *** [test] Error 2
```

System: `OSX 10.12`
`go version`: `go version go1.9 darwin/amd64`

Any ideas for me?

Thank you!

**Comment by MatthiasWinkelmann** [comment]
The interface of go-fuse apparently changed. It's fixed in https://github.com/MatthiasWinkelmann/redis-fs/commit/b6b98fa6fd9ce443f0c72550f83a9bd6a71b4858 and the current binary downloads. Run ```make clean``` ```make get-dept``` and ```make build``` (in that order).
